[BitTorrent]
Session\Port=31856
Session\QueueingSystemEnabled=false
Session\SSL\Port=32191

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()

[Preferences]
WebUI\Address=0.0.0.0
