[LegalNotice]
Accepted=true

[Preferences]
WebUI\Address=0.0.0.0
WebUI\Username=<%- username  %>
WebUI\Password_PBKDF2=@ByteArray(<%- passwordHash  %>)
WebUI\LocalHostAuthBypass=true
WebUI\HostHeaderValidation=false
WebUI\CSRFProtection=false
WebUI\ServerDomains=*
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=<%- authSubnetWhitelist  %>
